# Generated by Django 2.2.7 on 2019-12-04 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_items', '0003_auto_20191204_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('message', models.CharField(blank=True, max_length=256, null=True)),
                ('custom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='add_items.Pizza_compose')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='add_items.Pizza_menu')),
            ],
        ),
    ]
