# Generated by Django 2.2.7 on 2019-12-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dough_flour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flour', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Dough_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Dough_thickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Dough_thickness',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('ingredient', models.ManyToManyField(related_name='menu_ingredients', to='add_items.Ingredient')),
                ('sauce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_sauce', to='add_items.Sauce')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_compose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flour', models.ForeignKey(default='white', on_delete=django.db.models.deletion.CASCADE, related_name='pizza_flour', to='add_items.Dough_flour')),
                ('ingredient', models.ManyToManyField(related_name='compose_ingredients', to='add_items.Ingredient')),
                ('pizza_size', models.ForeignKey(default='small', on_delete=django.db.models.deletion.CASCADE, related_name='pizza_size', to='add_items.Dough_size')),
                ('sauce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compose_sauce', to='add_items.Sauce')),
                ('thickness', models.ForeignKey(default='thin', on_delete=django.db.models.deletion.CASCADE, related_name='pizza_thickness', to='add_items.Dough_thickness')),
            ],
        ),
    ]
