# Generated by Django 2.2.7 on 2019-12-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dough_size',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
