# Generated by Django 2.2.7 on 2019-12-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_items', '0002_dough_size_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dough_flour',
            name='add_fee',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dough_thickness',
            name='add_fee',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pizza_menu',
            name='price',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='sauce',
            name='add_fee',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(blank=True, default=3, null=True),
        ),
    ]
